global using System.Net;
global using System.Net.Http.Headers;
global using System.Net.Http.Json;
global using System.Text;
global using System.Text.Json;
global using FluentAssertions;
global using Microsoft.AspNetCore.Mvc.Testing;
global using RealEstateApp.Api.Tests.Fixtures;
global using Xunit;
